<a href="https://colab.research.google.com/github/VibhaeoM01/Machine-Learning-Algorithms-Materials/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy

In [1]:
import numpy as np

In [4]:
 arr=np.array([1,2,3,4,5])
 print(arr)
 print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
arr=np.array((1,2,3,4))
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [8]:
# 0d
arr=np.array(42)
print(arr)

42


In [17]:
# 1d

arr=np.array([1,2,3,4,5])
print(arr)
arr.shape

[1 2 3 4 5]


(5,)

In [19]:
#2d
arr=np.array([[1,2,3,4],[5,6,7,8]],dtype=float)
print(arr)
arr.shape

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


(2, 4)

Initial placeholders in numpy array

In [22]:
#all values as 0
x=np.zeros((4,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
#all values as 1
y=np.ones((2,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
#particaluar value
z=np.full((4,5),5)
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [27]:
#identity matrix
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [28]:
#random values
b=np.random.random((3,4))   #values between 0 to 1
print(b)

c=np.random.randint(10,100,(2,4))   #values between 10 to 100 as specified
print(c)

[[0.20856737 0.25979239 0.9467078  0.60348605]
 [0.71478295 0.3513002  0.50235294 0.49435617]
 [0.37374409 0.0538626  0.68505035 0.46008217]]
[[85 63 25 12]
 [49 92 18 99]]


In [31]:
#array of evenly space values
d=np.linspace(10,40,7)       #7 values between 10 to 40 which are evenly spaced
print(d)

[10. 15. 20. 25. 30. 35. 40.]


In [32]:
#evenly space with step specified
e=np.arange(10,40,5)   # 5 as step size
print(e)

[10 15 20 25 30 35]


In [34]:
#convert list to array
list1=[5,7,8,9]

np_array=np.array(list1)
print(np_array)
type(np_array)

[5 7 8 9]


numpy.ndarray

In [35]:
#number of dim
c.ndim

2

In [36]:
#no. of ele
c.size

8

In [37]:
#dtype in array
c.dtype

dtype('int64')

MATHEMATICAL OP. ON NP ARRAY

In [38]:
list1=[1,2,3,4]
list2=[6,7,8,9]
list3=list1+list2  #joins 2 list
print(list3)

[1, 2, 3, 4, 6, 7, 8, 9]


In [40]:
a1=np.array((1,2,3,4))
a2=np.array((6,7,8,9))
print(a1+a2)

[ 7  9 11 13]


In [49]:
a=np.random.randint(1,10,(5,5))
b=np.random.randint(1,10,(5,5))
print(a)
print(b)
print(np.add(a,b))     #print(a+b)
print(np.subtract(a,b))   #print(a-b)
print(np.multiply(a,b))   #print(a*b)
print(np.divide(a,b))    #print(a/b)

[[4 6 7 4 7]
 [4 7 3 1 7]
 [9 5 6 2 4]
 [1 1 9 1 7]
 [1 6 8 3 2]]
[[9 2 9 3 5]
 [8 2 7 2 7]
 [9 2 2 7 6]
 [7 5 6 8 5]
 [7 2 3 5 3]]
[[13  8 16  7 12]
 [12  9 10  3 14]
 [18  7  8  9 10]
 [ 8  6 15  9 12]
 [ 8  8 11  8  5]]
[[-5  4 -2  1  2]
 [-4  5 -4 -1  0]
 [ 0  3  4 -5 -2]
 [-6 -4  3 -7  2]
 [-6  4  5 -2 -1]]
[[36 12 63 12 35]
 [32 14 21  2 49]
 [81 10 12 14 24]
 [ 7  5 54  8 35]
 [ 7 12 24 15  6]]
[[0.44444444 3.         0.77777778 1.33333333 1.4       ]
 [0.5        3.5        0.42857143 0.5        1.        ]
 [1.         2.5        3.         0.28571429 0.66666667]
 [0.14285714 0.2        1.5        0.125      1.4       ]
 [0.14285714 3.         2.66666667 0.6        0.66666667]]


ARRAY MANIPULATION

In [50]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[6 8 1]
 [4 1 1]]
(2, 3)


In [53]:
#transpose
trans=np.transpose(array)
print(trans)
trans.shape

[[6 4]
 [8 1]
 [1 1]]


(3, 2)

In [56]:
#reshaping
a=np.random.randint(1,10,(2,3))
print(a)
print(a.shape)

[[1 2 7]
 [8 1 3]]
(2, 3)


In [59]:
b=a.reshape(3,2)

print(b)
print(b.shape)

[[1 2]
 [7 8]
 [1 3]]
(3, 2)
